# SurgeOS kernel_toolchain.cmake
# This file is used to set up the toolchain for building the SurgeOS kernel.

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i386)
set(SURGEOS_TARGET_TRIPLE_SUFFIX -elf)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
message(STATUS "Using ${CMAKE_SYSTEM_PROCESSOR}${SURGEOS_TARGET_TRIPLE_SUFFIX} toolchain")

# Cross compiler
set(SURGEOS_CROSS_COMPILER_PATH ${CMAKE_SOURCE_DIR}/.opt/bin/)
set(SURGEOS_CROSS_COMPILER_PREFIX ${CMAKE_SYSTEM_PROCESSOR}${SURGEOS_TARGET_TRIPLE_SUFFIX}-)

# Set compiler binaries
set(CMAKE_C_COMPILER "${SURGEOS_CROSS_COMPILER_PATH}${SURGEOS_CROSS_COMPILER_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${SURGEOS_CROSS_COMPILER_PATH}${SURGEOS_CROSS_COMPILER_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${SURGEOS_CROSS_COMPILER_PATH}${SURGEOS_CROSS_COMPILER_PREFIX}as")
set(CMAKE_LINKER "${SURGEOS_CROSS_COMPILER_PATH}${SURGEOS_CROSS_COMPILER_PREFIX}gcc")
set(CMAKE_ASM_NASM_COMPILER nasm)

# Compiler flags
set(CMAKE_C_FLAGS "-ffreestanding -Wall -Wextra -nostdlib" 
  CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-ffreestanding -Wall -Wextra -nostdlib -fno-exceptions"
  CACHE STRING "" FORCE)

